---
- name: Provisioning EC2 instance
  block:

    - name: Create security group
      amazon.aws.ec2_security_group:
        name: "{{ sec_group }}"
        description: "Sec group for app"
        region: "{{ region }}"
        aws_access_key: "{{ec2_access_key}}"  # From vault as defined
        aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined
        rules:                                # allows ssh on port 22
          - proto: all
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all traffic

    - name: Amazon EC2 | Create Key Pair      # Create key pair for ssh
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        aws_access_key: "{{ec2_access_key}}"  # From vault as defined
        aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined
        key_material: "{{ item }}"
      with_file: "{{ ssh_key }}.pub"

    - name: Start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ key_name }}"
        # vpc_subnet_id: "{{ vpc_id }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ sec_group }}"
        volumes:
        - device_name: /dev/sda1
          ebs:
            volume_size: "{{ volume_size }}"
            delete_on_termination: true
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        network:
          assign_public_ip: true
        image_id: "{{ image }}"
        tags:
          Environment: OpenStack