---
- name: Cleanup
  block:

    - name: Get instances facts
      ec2_instance_info:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        filters:
          instance-state-name: [ "pending", "running" ]
          "tag:Name": "{{ instance_name }}"
      register: result

    - name: Instance Info
      debug:
        msg: "Tags: {{ item.tags }}ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
      loop: "{{ result.instances }}"

    - name: Terminate EC2 instance
      amazon.aws.ec2_instance:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        state: "absent"
        region: "{{ region }}"
        instance_ids: "{{ item.instance_id }}"
      loop: "{{ result.instances }}"