---
- name: Create AMI
  block:

    - name: Get instances facts
      ec2_instance_info:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        filters:
          instance-state-name: [ "pending", "running" ]
          "tag:Name": "{{ instance_name }}"
      register: result

    - name: Instance Info
      debug:
        msg: "Tags: {{ item.tags }}ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
      loop: "{{ result.instances }}"

    - name: AMI Creation
      amazon.aws.ec2_ami:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        instance_id: "{{ item.instance_id }}"
        wait: true
        name: "{{ ami_name }}"
        tags:
          Name: "{{ ami_name }}"
          Service: TestService
      loop: "{{ result.instances }}"