# AWS playbook
---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: my_aws             # Key used for SSH
    region: eu-west-1            # Region may affect response and pricing
    image: ami-0905a3c97561e0b69 # ec2 ubuntu ami (HVM)
    id: "OpenStack single node"
    instance_type: t3.xlarge       # Choose instance type, check AWS for pricing
    volume_size: 120
    instance_name: OpenStack cluster- AMI
    ami_name: openstack_sigle_node_ami
    sec_group: "admin"
    ssh_user: ubuntu
    ssh_key: /home/victor/.ssh/my_aws

  roles:
    - role: roles/instance_init
    - role: roles/connect

- name: Install OpenStack Cluster
  hosts: remote
  become: true  # Run commands with elevated privileges if necessary
  gather_facts: true  # Gather facts about the remote host
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
  - role: roles/juju_bootstrap
  - role: roles/sunbeam

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    region: eu-west-1            # Region may affect response and pricing
    instance_name: OpenStack cluster- AMI
    ami_name: openstack_sigle_node_ami

  roles:
    - role: roles/ami_creation
    - role: roles/cleanup
